import { snowflakeIdentifier, type SnowflakeStorageConfig } from "./snowflake-client";

type SchemaConfig = Pick<SnowflakeStorageConfig, "database" | "schema" | "tableKind">;

export function snowflakeObjects(config: SchemaConfig) {
  const namespace = `${snowflakeIdentifier(config.database)}.${snowflakeIdentifier(config.schema)}`;
  const prefix = config.tableKind === "hybrid" ? "BFL_HT" : "BFL_ST";
  return (name: string) => `${namespace}.${snowflakeIdentifier(`${prefix}_${name}`)}`;
}

/** The same logical schema is deployable on standard and hybrid tables. */
export function snowflakeSetupStatements(config: SchemaConfig): string[] {
  const o = snowflakeObjects(config), table = config.tableKind === "hybrid" ? "HYBRID TABLE" : "TABLE";
  return [
    `CREATE ${table} IF NOT EXISTS ${o("WRITE_LOCK")} (ID VARCHAR(32) PRIMARY KEY, GENERATION NUMBER NOT NULL, REVISION_COUNTER NUMBER NOT NULL) AS SELECT 'writer', 0, 0`,
    `CREATE ${table} IF NOT EXISTS ${o("PROJECTS")} (PROJECT_ID VARCHAR(256) PRIMARY KEY, SNAPSHOT VARIANT NOT NULL, UPDATED_AT VARCHAR NOT NULL)`,
    `CREATE ${table} IF NOT EXISTS ${o("SOURCE_DOCUMENTS")} (PROJECT_ID VARCHAR(256) NOT NULL, DOCUMENT_ID VARCHAR(256) NOT NULL, DOCUMENT VARIANT NOT NULL, ORIGINAL_PATH VARCHAR NOT NULL, IMAGES VARIANT NOT NULL, PRIMARY KEY(PROJECT_ID,DOCUMENT_ID))`,
    `CREATE ${table} IF NOT EXISTS ${o("REVISIONS")} (ID NUMBER PRIMARY KEY, PROJECT_ID VARCHAR(256) NOT NULL, WORKFLOW_ID VARCHAR(256) NOT NULL, REVISION_NUMBER NUMBER NOT NULL, REVISION VARIANT NOT NULL, UNIQUE(PROJECT_ID,WORKFLOW_ID,REVISION_NUMBER))`,
    `CREATE STAGE IF NOT EXISTS ${o("SOURCES")} ENCRYPTION=(TYPE='SNOWFLAKE_SSE')`,
    `CREATE OR REPLACE VIEW ${o("WORKFLOWS")} AS SELECT P.PROJECT_ID, W.VALUE:id::VARCHAR AS WORKFLOW_ID, W.VALUE:name::VARCHAR AS NAME, COALESCE(W.VALUE:scenario::VARCHAR,'current') AS SCENARIO, W.VALUE AS WORKFLOW FROM ${o("PROJECTS")} P, LATERAL FLATTEN(INPUT=>P.SNAPSHOT:graph.workflows) W`,
    `CREATE OR REPLACE VIEW ${o("NODES")} AS SELECT P.PROJECT_ID, N.VALUE:id::VARCHAR AS NODE_ID, N.VALUE:kind::VARCHAR AS KIND, N.VALUE:label::VARCHAR AS LABEL, N.VALUE:workflowId::VARCHAR AS WORKFLOW_ID, N.VALUE:status::VARCHAR AS STATUS, N.VALUE AS NODE FROM ${o("PROJECTS")} P, LATERAL FLATTEN(INPUT=>P.SNAPSHOT:graph.nodes) N`,
    `CREATE OR REPLACE VIEW ${o("EDGES")} AS SELECT P.PROJECT_ID, E.VALUE:id::VARCHAR AS EDGE_ID, E.VALUE:source::VARCHAR AS SOURCE_ID, E.VALUE:target::VARCHAR AS TARGET_ID, E.VALUE:relation::VARCHAR AS RELATION, E.VALUE:status::VARCHAR AS STATUS, E.VALUE AS EDGE FROM ${o("PROJECTS")} P, LATERAL FLATTEN(INPUT=>P.SNAPSHOT:graph.edges) E`,
    `CREATE OR REPLACE VIEW ${o("DATA_FLOWS")} AS SELECT P.PROJECT_ID, F.VALUE:id::VARCHAR AS FLOW_ID, F.VALUE:sourceSystemId::VARCHAR AS SOURCE_SYSTEM_ID, F.VALUE:targetSystemId::VARCHAR AS TARGET_SYSTEM_ID, F.VALUE:status::VARCHAR AS STATUS, F.VALUE AS FLOW FROM ${o("PROJECTS")} P, LATERAL FLATTEN(INPUT=>P.SNAPSHOT:graph.dataFlows) F`,
    `CREATE OR REPLACE VIEW ${o("ACTIVITIES")} AS SELECT P.PROJECT_ID, A.VALUE:id::VARCHAR AS ACTIVITY_ID, A.VALUE:name::VARCHAR AS NAME, A.VALUE AS ACTIVITY FROM ${o("PROJECTS")} P, LATERAL FLATTEN(INPUT=>P.SNAPSHOT:graph.knowledge.activities) A`,
    `CREATE OR REPLACE VIEW ${o("CAPABILITIES")} AS SELECT A.PROJECT_ID, A.ACTIVITY_ID, C.VALUE:id::VARCHAR AS CAPABILITY_ID, C.VALUE:name::VARCHAR AS NAME, C.VALUE AS CAPABILITY FROM ${o("ACTIVITIES")} A, LATERAL FLATTEN(INPUT=>A.ACTIVITY:capabilities) C`,
    `CREATE OR REPLACE VIEW ${o("CAPABILITY_WORKFLOWS")} AS SELECT C.PROJECT_ID, C.ACTIVITY_ID, C.CAPABILITY_ID, W.VALUE::VARCHAR AS WORKFLOW_ID FROM ${o("CAPABILITIES")} C, LATERAL FLATTEN(INPUT=>C.CAPABILITY:workflowIds) W`,
    `CREATE OR REPLACE VIEW ${o("HANDOFFS")} AS SELECT P.PROJECT_ID, H.VALUE:id::VARCHAR AS HANDOFF_ID, H.VALUE:sourceWorkflowId::VARCHAR AS SOURCE_WORKFLOW_ID, H.VALUE:targetWorkflowId::VARCHAR AS TARGET_WORKFLOW_ID, H.VALUE:status::VARCHAR AS STATUS, H.VALUE AS HANDOFF FROM ${o("PROJECTS")} P, LATERAL FLATTEN(INPUT=>P.SNAPSHOT:graph.knowledge.handoffs) H`,
    `CREATE OR REPLACE VIEW ${o("MATERIAL_HANDOFFS")} AS SELECT W.PROJECT_ID, W.WORKFLOW_ID AS SOURCE_WORKFLOW_ID, H.VALUE:id::VARCHAR AS HANDOFF_ID, H.VALUE:targetWorkflowId::VARCHAR AS TARGET_WORKFLOW_ID, H.VALUE:dataContinuity::VARCHAR AS DATA_CONTINUITY, H.VALUE AS HANDOFF FROM ${o("WORKFLOWS")} W, LATERAL FLATTEN(INPUT=>W.WORKFLOW:landscape.materialHandoffs) H`,
    `CREATE OR REPLACE VIEW ${o("SYSTEM_CATEGORIES")} AS SELECT P.PROJECT_ID, C.VALUE:id::VARCHAR AS CATEGORY_ID, C.VALUE:name::VARCHAR AS NAME, C.VALUE AS CATEGORY FROM ${o("PROJECTS")} P, LATERAL FLATTEN(INPUT=>P.SNAPSHOT:graph.knowledge.categories) C`,
    `CREATE OR REPLACE VIEW ${o("SYSTEM_PROFILES")} AS SELECT P.PROJECT_ID, S.VALUE:systemId::VARCHAR AS SYSTEM_ID, S.VALUE:categoryId::VARCHAR AS CATEGORY_ID, S.VALUE:owner::VARCHAR AS OWNER, S.VALUE:certainty::VARCHAR AS STATUS, S.VALUE AS PROFILE FROM ${o("PROJECTS")} P, LATERAL FLATTEN(INPUT=>P.SNAPSHOT:graph.knowledge.systems) S`,
    `CREATE OR REPLACE VIEW ${o("SYSTEM_DEPENDENCIES")} AS SELECT S.PROJECT_ID, S.SYSTEM_ID, D.VALUE:systemId::VARCHAR AS PREREQUISITE_ID, D.VALUE:certainty::VARCHAR AS STATUS, D.VALUE AS DEPENDENCY FROM ${o("SYSTEM_PROFILES")} S, LATERAL FLATTEN(INPUT=>S.PROFILE:dependsOn) D`,
    // Usage is an actual process relation. Platform prerequisites and data transfers are separately queryable; they do not inflate this count.
    `CREATE OR REPLACE VIEW ${o("SYSTEM_USAGE")} AS SELECT DISTINCT S.PROJECT_ID, S.NODE_ID AS SYSTEM_ID, T.WORKFLOW_ID, T.NODE_ID AS PROCESS_ID, W.SCENARIO, E.RELATION, E.STATUS FROM ${o("EDGES")} E JOIN ${o("NODES")} S ON E.PROJECT_ID=S.PROJECT_ID AND S.KIND='system' AND (E.SOURCE_ID=S.NODE_ID OR E.TARGET_ID=S.NODE_ID) JOIN ${o("NODES")} T ON E.PROJECT_ID=T.PROJECT_ID AND T.KIND='process' AND (E.SOURCE_ID=T.NODE_ID OR E.TARGET_ID=T.NODE_ID) JOIN ${o("WORKFLOWS")} W ON T.PROJECT_ID=W.PROJECT_ID AND T.WORKFLOW_ID=W.WORKFLOW_ID WHERE E.RELATION IN ('uses','executes')`,
    `CREATE OR REPLACE VIEW ${o("SOURCE_UNITS")} AS SELECT D.PROJECT_ID, D.DOCUMENT_ID, U.VALUE:id::VARCHAR AS UNIT_ID, D.DOCUMENT:sha256::VARCHAR AS DOCUMENT_SHA256, D.DOCUMENT:lifecycle.state::VARCHAR AS LIFECYCLE_STATE, U.VALUE:location::VARCHAR AS LOCATION, U.VALUE AS SOURCE_UNIT FROM ${o("SOURCE_DOCUMENTS")} D, LATERAL FLATTEN(INPUT=>D.DOCUMENT:units) U`,
  ];
}

/** Data privileges for the deploy role. Creation/deploy privileges are configured in Snowflake's Apps setup. */
export function snowflakeDataGrants(config: SchemaConfig, role: string): string[] {
  const o=snowflakeObjects(config),r=snowflakeIdentifier(role),namespace=`${snowflakeIdentifier(config.database)}.${snowflakeIdentifier(config.schema)}`;
  const views=snowflakeSetupStatements(config).filter(sql=>sql.startsWith('CREATE OR REPLACE VIEW')).map(sql=>sql.match(/^CREATE OR REPLACE VIEW (\S+) AS /)![1]);
  return [`GRANT USAGE ON DATABASE ${snowflakeIdentifier(config.database)} TO ROLE ${r}`,`GRANT USAGE ON SCHEMA ${namespace} TO ROLE ${r}`,
    ...['WRITE_LOCK','PROJECTS','SOURCE_DOCUMENTS','REVISIONS'].map(name=>`GRANT SELECT, INSERT, UPDATE ON TABLE ${o(name)} TO ROLE ${r}`),
    ...views.map(view=>`GRANT SELECT ON VIEW ${view} TO ROLE ${r}`),`GRANT READ, WRITE ON STAGE ${o('SOURCES')} TO ROLE ${r}`];
}
